version: '3'

services:
    brevets:
        build: brevets/.
        command: python flask_brevets.py
        ports: 
          - "5001:5000"
        environment:
          MONGODB_HOSTNAME: brevets-db
        depends_on:
          - brevets-db
        volumes:
          - type: bind
            source: brevets/.
            target: /app
    brevets-db:
      image: mongo:5.0.5

